listaAgradecimiento = [
    "Gracias por tu opinión sobre el ambiente.",
    "Te agradezco mucho tu participación en la encuesta.",
    "Estoy muy agradecido por tu interés en el ambiente.",
    "Gracias por compartir tu punto de vista sobre el ambiente.",
    "Te estoy muy agradecido por tu aporte a la encuesta.",
    "Gracias por tu tiempo y compromiso con el ambiente.",
    "Te agradezco de corazón tu contribución a la encuesta.",
    "Estoy muy agradecido por tu sensibilidad hacia el ambiente.",
    "Gracias por tu honestidad y responsabilidad con el ambiente.",
    "Te estoy muy agradecido por tu valoración del ambiente.",
    "Gracias por tu cooperación y solidaridad con el ambiente.",
    "Te agradezco mucho tu implicación en la encuesta.",
    "Estoy muy agradecido por tu conocimiento sobre el ambiente.",
    "Gracias por tu feedback y sugerencias sobre el ambiente.",
    "Te estoy muy agradecido por tu actitud positiva hacia el ambiente.",
    "Gracias por tu disposición y colaboración con la encuesta.",
    "Te agradezco mucho tu apoyo y confianza en el ambiente.",
    "Estoy muy agradecido por tu entusiasmo y motivación por el ambiente.",
    "Gracias por tu experiencia y aprendizaje sobre el ambiente.",
    "Te estoy muy agradecido por tu reflexión y análisis sobre el ambiente.",
    "Gracias por tu información y datos sobre el ambiente.",
    "Te agradezco mucho tu opinión y criterio sobre el ambiente.",
    "Estoy muy agradecido por tu visión y perspectiva sobre el ambiente.",
    "Gracias por tu expresión y comunicación sobre el ambiente.",
    "Te estoy muy agradecido por tu comprensión y empatía con el ambiente.",
    "Gracias por tu observación y atención al ambiente.",
    "Te agradezco mucho tu respeto y cuidado del ambiente.",
    "Estoy muy agradecido por tu conciencia y acción por el ambiente.",
    "Gracias por tu creatividad e innovación para el ambiente.",
    "Te estoy muy agradecido por tu liderazgo e influencia en el ambiente.",
]
listaDatosRandomPlastico = [
    "Cada año se desechan 8 millones de toneladas de plástico en el océano, lo que representa una amenaza para la vida marina[^1^][1].",
    "El plástico se descompone en partículas más pequeñas, llamadas microplásticos, que se acumulan en los fondos marinos y afectan la salud de los organismos marinos[^1^][1].",
    "El plástico puede absorber toxinas del agua, lo que afecta la calidad del agua y puede contaminar los alimentos que consumimos[^1^][1].",
    "El plástico emite gases de efecto invernadero, como el dióxido de carbono y el metano, que contribuyen al cambio climático[^2^][2].",
    "El plástico es un material combustible, lo que significa que si se quema, puede emitir gases tóxicos que afectan la salud humana y el medio ambiente[^2^][2].",
    "El plástico se produce principalmente a partir de combustibles fósiles, lo que significa que su fabricación comporta una gran cantidad de emisiones de gases de efecto invernadero[^3^][3].",
    "El plástico es un material muy difícil de descomponer. Esto significa que los desechos plásticos se acumulan en los océanos, los ríos y los suelos, causando graves problemas de contaminación[^3^][3].",
    "El plástico provoca la pérdida de biodiversidad, ya que afecta a las especies de todo el planeta, especialmente a las marinas[^3^][3].",
    "El plástico es un material muy útil para la industria, pero su uso tiene un gran impacto en el medio ambiente. Se estima que solo el 9% del plástico producido se recicla[^3^][3].",
    "El plástico es uno de los principales contaminantes del medio ambiente. El plástico puede tener un impacto negativo en los océanos, la atmósfera, el suelo y la salud humana[^4^][4].",
    "Plástico amenaza la vida marina y la biodiversidad¹.",
    "Plástico se descompone en microplásticos que contaminan el agua¹.",
    "Plástico absorbe toxinas que pueden afectar la salud humana¹.",
    "Plástico emite gases de efecto invernadero que causan cambio climático².",
    "Plástico quema gases tóxicos que afectan la salud y el ambiente².",
    "Plástico se produce a partir de combustibles fósiles que emiten CO2³.",
    "Plástico se acumula en los océanos, los ríos y los suelos³.",
    "Plástico provoca la pérdida de biodiversidad terrestre y marina³.",
    "Plástico es un material duradero que se usa para objetos desechables³.",
    "Plástico es uno de los principales contaminantes del medio ambiente⁴.",
    "Plástico forma islas gigantes en los océanos donde confluyen las corrientes¹.",
    "Plástico provoca laceraciones, heridas internas y muerte a los animales¹.",
    "Plástico contamina los alimentos que consumimos con plástico¹.",
    "Plástico contribuye al calentamiento global y sus consecuencias².",
    "Plástico es un material combustible que puede provocar incendios².",
    "Plástico requiere mucha energía y recursos para su fabricación³.",
    "Plástico es muy difícil de descomponer y reciclar³.",
    "Plástico altera el equilibrio ecológico y natural del planeta³.",
    "Plástico es un material muy útil pero con un gran impacto negativo⁴.",
    "Plástico se ha convertido en uno de los retos medioambientales más urgentes⁴.",
    "Plástico afecta la calidad del agua y puede provocar escasez hídrica¹.",
    "Plástico afecta la salud de los organismos marinos y su reproducción¹.",
    "Plástico puede liberar sustancias químicas que alteran el sistema hormonal¹.",
    "Plástico aumenta la huella de carbono y la contaminación del aire².",
    "Plástico puede generar residuos peligrosos que requieren un tratamiento especial².",
    "Plástico depende de una fuente no renovable y limitada como el petróleo³.",
    "Plástico genera una gran cantidad de residuos que ocupan espacio y recursos³.",
    "Plástico pone en riesgo la supervivencia de muchas especies en peligro de extinción³.",
    "Plástico se ha instalado en nuestras vidas para siempre y es difícil evitarlo⁴.",
    "Plástico se acumula en el medioambiente año tras año sin desaparecer⁴."
]
